ace/scrape.py

Fixes issue where function to check for open access was not linked anywhere

Skip if pmc open access found, link function

---

ace/scrape.py

- Adds log to indicate PMC Open Access skip reason
- Try/Catch for missing author

Add log, and catch for missing author

---

ace/scrape.py

- Adds a `_quit_driver` function
- Fixes issues w/ Chrome instantiation

FIX: Driver instantiation / quitting issues

---

ace/scrape.py

- Quick fix to make the error message for "no PMC found" more specific

FIX: Change error message to be more specific

---

.github/workflows/test.yml
ace/scrape.py
ace/tests/cassettes/test_ace/test_journal_scraping.yaml
ace/utils.py

[FIX] pubmedapi

---

ace/scrape.py

PMC has some failed article scrapes now too.

[FIX] failed scrape string

---

ace/scrape.py

adding a few more based on results.

[FIX] add another failure to scrape status

---

ace/scrape.py
ace/tests/test_ace.py
requirements.txt

selenium base has fixed several issues related to undetected-chromedriver

[ENH] use seleniumbase

---

ace/scrape.py

write the pmcids to file so they can be accessed with pubget.

[ENH] write skipped pmcids to file

---

ace/scrape.py
ace/sources.py
ace/sources/PMC.json

fix errors for finding and ingesting PMC sources.

[FIX] pmc source

---

ace/sources.py

wiley tables from recent scrape are being missed.

[FIX] wiley table

---

ace/sources.py
ace/tests/test_ace.py
ace/tests/weird_data/20159144.html

branches got confused, this is fixing the PMC embedded tables.

[FIX] PMC table

---

ace/sources.py
ace/tests/test_ace.py
ace/tests/weird_data/36196770.html

```
INFO   ingest  Processing article /data/alejandro/projects/neurosynth_scrape/articles/html/Epilepsia/36196770.html...
INFO:ace.ingest:Processing article /data/alejandro/projects/neurosynth_scrape/articles/html/Epilepsia/36196770.html...
INFO   scrape  Retrieving metadata from file /data/alejandro/projects/neurosynth_scrape/pm_metadata/36196770...
INFO:ace.scrape:Retrieving metadata from file /data/alejandro/projects/neurosynth_scrape/pm_metadata/36196770...
INFO   sources Found 2 tables.
INFO:ace.sources:Found 2 tables.
Traceback (most recent call last):
File "create_db_and_add_articles.py", line 32, in <module>
missing_sources = add_articles(
File "/home/james/ACE/ace/ingest.py", line 67, in add_articles
article = source.parse_article(html, pmid, metadata_dir=metadata_dir, **kwargs) …
```

[FIX] wiley label

---

ace/sources.py
ace/tests/test_ace.py
ace/tests/weird_data/12417470.html

sciencedirect has a few weird tables that we are missing, this is an attempt to capture some of them.

[FIX] try to parse weird tables

---

ace/sources.py
ace/tableparser.py
ace/tests/test_ace.py
ace/tests/weird_data/26021218.html

`<br>` tags causing rows to join strangely.

[FIX] br tags

---

ace/scrape.py

calling the module instead of the function

[FIX] call to random

---

ace/scrape.py

add back in the lengthy process of checking metadata, but this help downloading files in the "right" directory.

[FIX] journal

---

ace/scrape.py
ace/tests/test_ace.py

add index_pmid option to check all output for repeats.

[ENH] remove all existing pmids

---

ace/sources/HighWire.json
ace/sources/JournalOfCognitiveNeuroscience.json
ace/sources/ScienceDirect.json
ace/sources/Springer.json
ace/tests/cassettes/test_ace/test_database_processing_stream.yaml
ace/tests/test_ace.py
ace/tests/weird_data/18439804.html

add the older source identifiers back into the json files.

[FIX] older source identifiers

---

ace/sources.py
ace/sources/OldSpringer.json
ace/sources/Springer.json
ace/tests/test_ace.py
ace/tests/weird_data/23813017.html

[FIX] add old Springer Parser

---

ace/sources.py
ace/tests/test_ace.py
ace/tests/weird_data/28432782.html

```python
Traceback (most recent call last):
File "ace_create_db_and_add_articles.py", line 32, in <module>
missing_sources = add_articles(
File "/home/james/ACE/ace/ingest.py", line 67, in add_articles
article = source.parse_article(html, pmid, metadata_dir=metadata_dir, **kwargs)
File "/home/james/ACE/ace/sources.py", line 671, in parse_article
t = self.parse_table(table_html)
File "/home/james/ACE/ace/sources.py", line 698, in parse_table
return super(WileySource, self).parse_table(table)
File "/home/james/ACE/ace/sources.py", line 219, in parse_table
n_cols = max([n_cols_in_row(
ValueError: max() arg is an empty sequence
```

[FIX] handle empty table

---

ace/sources.py

handle case when table expansions can no longer be downloaded

[FIX] table download

---

ace/tableparser.py
ace/tests/test_ace.py
ace/tests/weird_data/38990127.html

[FIX] parse tables with newlines

---

ace/sources.py

Improves raw text extraction w/ Mozilla's readability

Improve text extraction with readability
